//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptolens {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VATCalculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;BE&quot;:21,
        ///    &quot;BG&quot;:20,
        ///    &quot;CZ&quot;:21,
        ///    &quot;DK&quot;:25,
        ///    &quot;DE&quot;:19,
        ///    &quot;EE&quot;:20,
        ///    &quot;IE&quot;:23,
        ///    &quot;EL&quot;:24,
        ///    &quot;ES&quot;:21,
        ///    &quot;FR&quot;:20,
        ///    &quot;HR&quot;:20,
        ///    &quot;IT&quot;:22,
        ///    &quot;CY&quot;:19,
        ///    &quot;LV&quot;:21,
        ///    &quot;LT&quot;:21,
        ///    &quot;LU&quot;:17,
        ///    &quot;HU&quot;:27,
        ///    &quot;MT&quot;:18,
        ///    &quot;NL&quot;:21,
        ///    &quot;AT&quot;:20,
        ///    &quot;PL&quot;:23,
        ///    &quot;PT&quot;:23,
        ///    &quot;RO&quot;:19,
        ///    &quot;SI&quot;:22,
        ///    &quot;SK&quot;:20,
        ///    &quot;FI&quot;:24,
        ///    &quot;SE&quot;:25,
        ///    &quot;UK&quot;:20
        ///}.
        /// </summary>
        internal static string ISO2Country {
            get {
                return ResourceManager.GetString("ISO2Country", resourceCulture);
            }
        }
    }
}
